### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by SanaTameem** [batoolfatima2135/Leaderboard#4]
Hi @batoolfatima2135 👋🏻 
You have done a great job so far but there are always more ways for improvement.
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7a3370696f6b77663057504838314d4f68752f67697068792e676966](https://github.com/batoolfatima2135/Leaderboard/assets/71990110/4e31dacb-0702-4c26-b348-6c7ef7a50586)

- Try to deploy your project and add a link to the live demo section of your README.md file or if there is no need for deployment kindly remove the live demo section from your README file.

- Try to sort the data that you are fetching from the API so the scores should be visible in descending order.

**Comment by batoolfatima2135** [comment]
Hey @SanaTameem! Thank you so much for taking some time and suggesting me the changes. 😇 I have implemented all of them. 
<img src="https://media3.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif"/>
Thanks once again and keep supporting!
Happy coding 😊
